const $=s=>document.querySelector(s);
async function api(path,options={}){const r=await fetch(path,{credentials:"include",...options});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||"Request failed");return d}
function showAdmin(){ $("#loginView").classList.add("hidden"); $("#adminView").classList.remove("hidden"); loadProducts(); }
async function checkSession(){try{await api("/api/admin-session");showAdmin()}catch{}}
$("#loginForm").addEventListener("submit",async e=>{e.preventDefault();$("#loginError").textContent="";try{await api("/api/admin-login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password:$("#password").value})});$("#password").value="";showAdmin()}catch(err){$("#loginError").textContent=err.message}});
$("#logoutButton").addEventListener("click",async()=>{await api("/api/admin-logout",{method:"POST"});location.reload()});
$("#productForm").addEventListener("submit",async e=>{e.preventDefault();const fd=new FormData(e.target);const product=Object.fromEntries(fd.entries());product.price=Number(product.price);try{await api("/api/products",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(product)});e.target.reset();loadProducts()}catch(err){alert(err.message)}});
async function loadProducts(){try{const d=await api("/api/products");$("#productCount").textContent=d.products.length;$("#productList").innerHTML=d.products.map(p=>`<div class="product-row"><div><strong>${escapeHtml(p.name)}</strong><br><small>${escapeHtml(p.category)} · ₹${p.price}</small></div><button class="delete" data-id="${p.id}">Delete</button></div>`).join("")||"<p>No products yet.</p>";document.querySelectorAll(".delete").forEach(b=>b.onclick=async()=>{if(confirm("Delete this product?")){await api("/api/products",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:b.dataset.id})});loadProducts()}})}catch(err){$("#productList").textContent=err.message}}
$("#trackingForm").addEventListener("submit",async e=>{e.preventDefault();const fd=new FormData(e.target);try{await api("/api/tracking",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(fd.entries()))});$("#trackingMessage").textContent="Tracking ID saved."}catch(err){$("#trackingMessage").textContent=err.message}});
function escapeHtml(s=""){return s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
checkSession();
